### ISSUE TITLE
Dead link in README

### ISSUE THREAD

**Issue by adriaandegroot** [libts/tslib#171]
In the README text (what GitHub shows when you visit https://github.com/libts/tslib) this text:

> If you're lucky, you'll find some unofficial testing builds for Windows or other platforms here.

Links to Martin's home site, which has moved, and the referenced page is gone.

**Comment by merge** [comment]
feel free to create a PR to remove it

Am 15. April 2020 00:08:47 MESZ schrieb Adriaan de Groot <notifications@github.com>:
>In the README text (what GitHub shows when you visit
>https://github.com/libts/tslib) this text:
>
>> If you're lucky, you'll find some unofficial testing builds for
>Windows or other platforms here.
>
>Links to Martin's home site, which has moved, and the referenced page
>is gone.

-- 
Martin Kepplinger
xmpp: martink@jabber.at
sent from mobile
