### ISSUE TITLE
Build instructions do not work as-is.

### ISSUE THREAD

**Issue by ajduncan** [libts/tslib#179]
Sorry in advance if I misunderstood the instructions.  Just giving some hopefully friendly feedback on documentation, in case it's confusing or frustrating to a new user wanting to compile tslib from source.

1. The standard "./configure; make; make install" does not work as referenced: "Apart from building the latest tarball release, running ./configure, make and make install, ..." - maybe this text should be removed?

2. There is no configure script to run ./configure as-is.  The instructions aren't clear in README.md, regarding "Use the configure script to enable only the modules you need."  ... ./configure --enable-static, etc, does not seem clear.

Using cmake works to compile and install tslib.

**Comment by merge** [comment]
instructions only apply to release packages. for the git checkout, you need to run autogen.sh first
