### ISSUE TITLE
 DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package 

### ISSUE THREAD

**Issue by billpeace** [libts/tslib#185]
[DEP0148] DeprecationWarning: Use of deprecated folder mapping "./" in the "exports" field module resolution of the package at E:\Project\aspnet-zero-core-5.5.0\Nangular\node_modules\tslib\package.json.
Update this package.json to use a subpath pattern like "./*".
(Use `node --trace-deprecation ...` to show where the warning was created)

node -v
v15.3.0

npm -v
6.14.9

**Comment by merge** [comment]
since nodejs has nothing to do with this library project, do you mean to file this issue against https://www.npmjs.com/package/tslib ?
